Jenkinsfile
New file for Jenkins pipeline.  Copied from ui-toolkit and modified with new project naming.
=> ci: add jenkinsfile for scanning

package-lock.json, package.json
=> build(version): bump to v2.0.2

.github/workflows/ci.yml
closes AB#4318
Upgrade CI from Node 14.x to new LTS 16.x
=> ci(node): bump from 14.x to 16.x

.github/workflows/release.yml, .releaserc.json, package.json
adds automated releases using semantic-release
=> ci(semantic-release): adds automated releases

.github/workflows/release.yml
=> ci(release.yml): fixes README.md reference

CHANGELOG.md, README.md
=> fix(deps): release dependency updates since 2.0.3

package-lock.json, package.json
=> fix(deps): update  @open-amt-cloud-toolkit/ui-toolkit to v2.0.5

README.md
=> fix(kvm): scrolling offset for mouse is fixed in ui-toolkit 2.0.6

.github/workflows/ci.yml, .gitignore, package-lock.json, package.json, projects/kvm/karma.conf.js, projects/sol/karma.conf.js
=> ci(karma): add junit reports

.github/workflows/ci.yml
=> ci: remove dist publish step in lieu of semantic release

.github/workflows/projectsSync.yaml
=> ci: add project sync to ui-toolkit-angular

package-lock.json, package.json
=> fix: updated version in package.json

package-lock.json, package.json
=> build(deps-dev): bump angular  from 15.2.2 to 15.2.4

.github/workflows/codeql-analysis.yml
=> ci: update codeql to v2

.github/workflows/ci.yml
=> ci(deps): bump codecov to 3.1.3

package-lock.json
=> build(deps): update socket.io engine

.github/workflows/ci.yml, .github/workflows/release.yml
=> ci: updated semantic release configuration

package-lock.json, package.json
=> build: bump angular cdk, cli  to 16.1.0 and core to 16.1.1

package-lock.json, package.json
=> build: bump @angular/cdk to v16.1.1

package-lock.json, package.json
=> build: bump @angular/cli to 16.2.7

.github/workflows/ci.yml, .github/workflows/release.yml
=> ci: update to node 20

package-lock.json, package.json
=> build: bump angular/cdk to 16.2.11 and cli to 16.2.9

package-lock.json, package.json
=> fix: move ui-toolkit to peer dependency

.github/workflows/release.yml
=> ci: automatically updates package.json and changelog during release

.releaserc.json
=> ci: remove git publish

ider/src/ider.component.ts, kvm/src/kvm.component.ts, package-lock.json, package.json, sol/src/sol.component.ts
=> feat: add support for multiple redirection connections

.releaserc.json
=> ci: update package.json during release

.github/workflows/release.yml
=> ci: set persist credentials to false for release

package.json
=> chore: update build tasks, package.json and changelog

package-lock.json, package.json
=> build: bump @angular/core to 17.3.4

ider/src/ider.component.spec.ts, ider/src/ider.component.ts, package-lock.json, package.json
=> fix: invalid subprotocol during IDER connection

package-lock.json, package.json, sol/src/sol.component.spec.ts, sol/src/sol.component.ts, sol/src/terminal/terminal.component.ts
=> build: replaced xterm with @xterm/xterm

.github/workflows/semantic.yml
=> ci: update permissions on semantic.yml

package-lock.json, package.json
=> chore: updated ui-toolkit to latest version 3.2.6

package-lock.json, package.json
@angular-eslint/schematics  18.1.0 -> 18.2.0
@angular/cdk                        18.1.2 -> 18.1.3
@angular/cli                          18.1.2 -> 18.1.3
@angular/core                       18.1.2 -> 18.1.3
=> build: bump angular

package-lock.json, package.json
@angular/cdk             18.2.8 -> 18.2.9
@angular/cli             18.2.8 -> 18.2.9
=> build(deps): bump angular to 18.2.9

CHANGELOG.md
BREAKING CHANGE: move to angular 19
=> chore!: address incorrectly released breaking change

CHANGELOG.md, kvm/src/kvm.component.css, kvm/src/kvm.component.ts, package-lock.json, package.json
=> feat: allow KVM fullscreen

.github/workflows/release.yml, README.md
=> ci: add @device-management-toolkit publishing for ui-toolkit-angular

README.md, ider/src/ider.component.spec.ts, ider/src/ider.component.ts, kvm/src/kvm.component.spec.ts, kvm/src/kvm.component.ts, package-lock.json, package.json, sol/src/sol.component.spec.ts, sol/src/sol.component.ts
=> build(deps): move to @device-management-toolkit name

.github/workflows/release.yml
=> ci: add registry-url for node

README.md
=> chore: release @device-management-toolkit
